name: Export Extensions List

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at 00:00 UTC
  workflow_dispatch:     # Allows manual trigger

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      # Check out the current (empty) repository so that generate_extensions.sh is available.
      - name: Checkout self repository
        uses: actions/checkout@v3

      # Clone the Raycast extensions repository from GitHub.
      - name: Clone raycast extensions repository
        run: git clone https://github.com/raycast/extensions.git raycast_extensions

      # Run the export script on the cloned repository.
      - name: Run export script
        run: |
          cd raycast_extensions
          # Make sure the script is executable.
          chmod +x ../generate_extensions.sh
          # Run the script; it will create an "extensions.txt" in the current directory.
          ../generate_extensions.sh

      # Copy the generated file to a temporary output directory.
      - name: Copy generated file to output folder
        run: |
          mkdir -p out
          cp raycast_extensions/extensions.txt out/extensions.txt

      # Commit and push the file to an orphan branch named "extensions-list" in your repository.
      - name: Commit and push extensions.txt to orphan branch
        run: |
          cd out
          git init
          git checkout -b extensions-list
          # Set up Git user info.
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add extensions.txt
          git commit -m "Update extensions list [skip ci]"
          # Push the orphan branch to the repository using the provided GITHUB_TOKEN.
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push -f origin extensions-list